---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: escreveaqui-api-docs-auth
  namespace: escreveaqui
spec:
  encryptedData:
    users: AgAK/E8gOA3vDfhj0zzJP0tH86oFPTSvHn/81k2+dvtCdoLP4y6IV+55c0mkjb1K6UEAhzrYP+j0lLsBp7K4V0JAbemNdXjq5FojMWuCjTR005ffJbUY0OFFSU+BythKbkRVZtvk84mfsHrYf4On0hP/e6NibrZE/YXyWpXy94+udMyJNqUtRGC7h7IYfJAKHHIMxXxk9OpPjC7/3ZLgv7+tND+XnBKay8wqAEnaUqqMNZVcCbyWOCpTmDcYXTbeatt9NVpAtvuL4HpQLCb31fibgNL0R72Z/+fw8d5WRENYeF8uBWi3Q0MhmJNFG+1Ltqd0+l2RxGNKweYfIdtaag3xtqMM34obW3WJiiXK8zEDVsD5BC9TWSguDc+dskV/paxaNqUA2Bmuli81UAJPcn0cH16AbKEt6yKrn+cLQLm76EqsHFxMW9blSLujwEychov39vOKet2La5XSiEcRT/Fp867qa+NiAI3f+ulm83MENwiDVLLAdBSSLjxdgyQilftDO0NVjY6/Wwh0RMOj9s8J/KvMZ7/AVMqJr4hxPMwtuRkOAt10yhY4JU82nrWSgd3k0j97ksnxzaAMDuOIHtJw1HXxNVZPF85p2ihVnqCmirAkGM6oE7pFH92l5YHyt7ncoVhXvkSKiqcMqahc4CXeVu7rP9WD0j+nEvYGON/qUzdult5oGqFPh/juMFw5PHKUPYB0EQyQgDVgFllf3h8krBcIL5aTvnhvg5NjodalR0hpddaeWK1MQ09NboLXUXJN1thXGRGRUM8srN5zz9TONepX4JBaUw==
  template:
    metadata:
      creationTimestamp: null
      name: escreveaqui-api-docs-auth
      namespace: escreveaqui
