apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: escreveaqui-db-data
  namespace: escreveaqui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
