apiVersion: apps/v1
kind: Deployment
metadata:
  name: escreveaqui-db
  namespace: escreveaqui
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: escreveaqui-db
  template:
    metadata:
      labels:
        app: escreveaqui-db
    spec:
      containers:
        - name: postgresql
          image: docker.io/postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: escreveaqui-db
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: escreveaqui-db
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: escreveaqui-db
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - escreveaqui
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - escreveaqui
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: escreveaqui-db-data
