---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: escreveaqui-s3
  namespace: escreveaqui
spec:
  encryptedData:
    S3_ACCESS_KEY: AgAlhmRqqT9HAYDCmgCxXXUmEIL9IinGB3l1srNai/FGs+R2zueuN9o6XnblJARHPCXT9zN8OWOtrTQCd2UjfYmR6n8rm/DLuLEkhNI1teQTDRWreKQHAj8uZdOfo/4GPS5yhT+7QAJx+AkDOolEZBLt8p/cYtt1meZjaqZGVprGlkICgKGHO8AFRVDczSAix3tl5FAdOxeemHzHwraRk3tYGYG6bb1/LhDYZCgCF+x+U/+QBN7Lrs2eew997KIqvkTp5DP2RSuY2pdiUQcdh/1JNlxQSuTiBZ9C0ET3kohnLrGWzv5MHYMgpYW/uqfH6zD2+wdPOHrDsGxx2G22pEXx9+6YnP4YGWlDIfs08+4oVKuwmfUnD8u2hgRCngXucerAW0kFQOh699r7o5h2V2JwUCWPhSdHlAP6ogyM0JnQ336+uGaMyOyf4lRHAqNe7JEX9z2zuVGsCfY16XAJ6Ft+HWPxn3KlD6hz7K523ZwECwMi9K5JfEg6rh1FHTcyQorJ99y0dt3lOxjw66uhN2BiQMrzUp7ni7PtEK6IDct/FvqYZYLdPoHU2PpyROl3q2gEGloI+f4P4JYsAB1YQXzzcXmfWcbD27DqnsUekBBWf0Gz5jQLArLFrUN/uvu5qqnJFNUig90rZvz8NE8oPatSDV2rP4QZ/xL4LdZzJb0OFqyXofmZ5SS+09+6I/gYe1WLNRM7V5SVH7mPuaLlCuW9hHdIqzCOwuiUnDCq3yqysg==
    S3_SECRET_KEY: AgB972kXUJg8ynVJTqX92FvrPZTCRY2H5p0zmUU50W9SMFk6OC8A/AjMZChnoOVLgeibqcT35PgtE1Z97ZnRNXQhXDZamVcu0GV1OZU4SZnEQHV6WbAcdY6WpWpEgi3DYnSSQzTJrBjlx/hxjSD6FFRjp4BhYLvpQjWBzSfJ/u48c1+wBu6btGlwZaPKq8tLyGqJU4PPc5AivEm3IX1Qpg9f1Q5bbZRRSREenS+Id5rhrvzvCtLIj7RMl2In69leLQ1K2oCeB+R/0BbprmSQiBu/uuE14MtNs2rYJjpWtEa98mH29Xkc1K1hmzHTtXhdliaAFMZu/NE0SCr1chY0LE9T2Aw2GcxiVWnwzCk8gyXFl6r8hzrbA0X46+ZkeBaHy4QqopeXKNm99ADSiB3DE1iwtn4FZs496zFmlIVsEczEOTsNAdYfBJSnq41hcoT10ec+ixMPa4CeT6Bg5ZzIl7LtDeYzeP2G8xYVtlNlTwrcq806Zvb2+qHyZOKBtXeyYqRoPef4CBmbkamH7yGFMT7DGAKh4EQ0gwkk/qSeZSVlhiTgMtzfkoptwWvBSSKKQ5eG48KF1WhX3a/DY1G9ptii1KzOqMUNmm2vAOGN5cMX4WeXA2XPZf53XYRPPaldpAH746PGT09qrAdzUMN+GYJ/oXaZ8NN4Hamf8+kXJkOiXkpvaKRckgqbWi8v9cRjjM/6/awM/G22wanbmvXrlH6+id4Uud8oJM4JSeAvyl+jNQ==
  template:
    metadata:
      name: escreveaqui-s3
      namespace: escreveaqui
